### ISSUE TITLE
P-FTINT-1-1 board J3 and J4 spacing issue

### ISSUE THREAD

**Issue by sujitth** [Azure/azure-sphere-hardware-designs#24]
The space between the connectorJ3 and J4 is not enough to connect 2 cables simultaneously.

It would be better to change it to 10pin IDC box connectors so that 2 cables can be attached at a time.

**Comment by dhe-engineer** [comment]
> The space between the connectorJ3 and J4 is not enough to connect 2 cables simultaneously.
> 
> It would be better to change it to 10pin IDC box connectors so that 2 cables can be attached at a time.


J3 and J4 on the P-FTINT-1-1 board connect the service, recovery, and debug signals from the FTDI chip to the MT3620.
Please feel free to change these interfaces  to the format that is most suitable for your workflow.
