### ISSUE TITLE
P-FTINT-1-1 Altium Files

### ISSUE THREAD

**Issue by EHUbels** [Azure/azure-sphere-hardware-designs#26]
Would it not make sense that MS makes those files available and a more (lower) cost alternative than Altium Designer, for startups Altium Designer is way to expensive!

**Comment by dhe-engineer** [comment]
> Would it not make sense that MS makes those files available and a more (lower) cost alternative than Altium Designer, for startups Altium Designer is way to expensive!


Thank you for reaching out regarding the design files in Altium format.
The schematics, bill of materials, and production Gerber files are also provided in other formats along with the Altium design files for easy access.
Most major design tools and popular free design tools support the conversion of Altium design files into native formats.
Please feel free to covert the Altium files to your desired tool format using their supported procedures.
